name: Trigger CI/CD
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
    
jobs:
  trigger-downstream-workflow:
    name: Trigger downstream workflow
    runs-on: ubuntu-latest
    steps:
      - name: Trigger downstream workflow
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        run: |
          curl -X POST \
          -H "Authorization: Bearer ${{secrets.ACTIONS_KEY}}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/hleb-kastseika/hleb-dev-website/actions/workflows/firebase-hosting-merge.yml/dispatches \
          -d '{"ref": "master"}'
